apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-deployment
  labels:
    app: cluster
  spec:
    replicas: 3
    selector:
      matchLabels:
        app: cluster
    template:
      metadata:
        labels:
          app: cluster
      spec:
        containers:
        - name: cluster-deployment
          image: bsandu1/cicd