name: learn-github-actions
on: [push]
jobs:
  Build-Docker-Image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERPASS }} | docker login -u bsandu1 --password-stdin
      - name: Building docker image
        run: docker build . -t bsandu1/cicd
      - name: Pushing docker image
        run: docker push bsandu1/cicd:latest
  Email: 
    needs: Build-Docker-Image
    runs-on: ubuntu-latest
    steps:
      - name: emailed successfully
        run: echo pretending to email
  Deploy-to-cluster:
    needs: Email
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: deployed to cluster
        uses: danielr1996/kubectl-action@1.0.0
        name: Deploy
        with:
          kubeconfig: ${{ secrets.KUBECONFIG }}
          args: apply -f customdeployment.yaml